### ISSUE TITLE
Ignore virtual dlls

### ISSUE THREAD

**Issue by MehdiChinoune** [nurupo/mingw-ldd#1]
When executing mingw-ldd to fetch dependencies of a PEFILE, I get a long list of  files like `api-ms-win-***.dll => not found`.
It turns out that these dlls are virtual on Windows 10 as they are part of other dlls.
I think they should be ignored if the dlls providing them were found.

**Comment by MehdiChinoune** [comment]
It looks like this project is abandoned. Close

**Comment by nurupo** [comment]
>I think they should be ignored if the dlls providing them were found.

It sounds like there is no easy way to find what provides them. Only `apisetschema.dll` knows the mapping of a virtual dll to a real dll, and then it might differ from a system to a system. Not sure what can be done to resolve those, as `apisetschema.dll` doesn't offer any interface for applications to query this, there are only some binary hacks that work only on x86_64 floating around on the internet, and then they are not in Python and are not cross-platform.

If you just want to ignore the output of those, you can do so on your own, there is no need to modify mingw-ldd, e.g.

```python
./mingw-ldd.py foo.dll --dll-lookup-dirs "${PWD}" | grep -v 'api-ms-win-'
```

**Comment by nurupo** [comment]
Added a section on this to README: https://github.com/nurupo/mingw-ldd#known-issues.
